services:
  - type: web
    name: projeto-x
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /login.jsp
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx512m -Xms256m
